import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FloeProvider } from "@floe/next";

const InterFont = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <FloeProvider>
        <body className={`${InterFont.className} bg-white dark:bg-zinc-900`}>
          {children}
        </body>
      </FloeProvider>
    </html>
  );
}
